{
 "title": "Lynk Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "404 Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(lynk_urls_not_found_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URLs Shortened/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(lynk_urls_shortened_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirects/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(lynk_urls_redirected_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}