apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lynk
  labels:
    release: prometheus
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: lynk
  endpoints:
  - port: http
    path: /metrics
    interval: 30s